# 1. Conexão com o Supabase
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.dtounbzllatfqwyoguuy
spring.datasource.password=${DB_PASSWORD}

# 2. Configuração do Hibernate (criação automática das tabelas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 3. Nome da aplicação e porta
spring.application.name=chamada-api
server.port=8080